#!/bin/bash
if [ $(whoami) != "root" ]
then
        sudo ./$0
        exit
else
	# Create directories
	mkdir /etc/dynamic_hosts &> /dev/null

	# Create configuration file
	touch /etc/dynamic_hosts/hosts

	# Install programm files
	cp dynamic-hosts-update /usr/local/bin/dynamic-hosts-update
	cp dynamic-hosts-cronjob /usr/local/bin/dynamic-hosts-cronjob

	# Add as cronjob
	if ! [[ $(crontab -l 2> /dev/null) = *"dynamic-hosts-cronjob"* ]]
	then
		crontab -l 2> /dev/null | { cat; echo "* * * * * /usr/local/bin/dynamic-hosts-cronjob"; echo " "; } | crontab -
	fi
fi
